### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by tingjiangcao** [Ftbom/Aria2Manager#3]
1.下载release应用，提示服务器连接失败，底下状态灯显示红色

2.下载编译源码，新版vsstudio打不开，提示setup.vdproj不支持

**Comment by Ftbom** [comment]
1. 目前发布的版本中没有包含aria2程序，需要额外运行aria2程序才可以连接
2. setup.vdproj用于将程序打包成安装包，VS需要安装Microsoft Visual Studio Installer Projects插件才可以打开
   >目前还没有计划将程序打包成安装包，只是添加了打包项目

**Comment by Ftbom** [comment]
自带aria2的版本还有bug，以后再发布

**Comment by tingjiangcao** [comment]
好的

**Comment by Ftbom** [comment]
[内置aria2程序的版本](https://github.com/Ftbom/Aria2Manager/releases/tag/v1.0.2)已发布。启动程序后会运行aria2进行连接，无需额外运行aria2
